--AGREGA AL FINAL DE LA CONSULTA UN TEXTO PARA EL CASO QUE SE ENCUENTREN MAS DE UN REGISTRO
--EJEMPLO 1 
SELECT top 1 PERS.NOMBRES+'  ' FROM GESTIONPREDIAL.PROPIETARIOS_PREDIOS PROP_PRED 
					INNER JOIN GESTIONPREDIAL.PREDIOS PRED ON PROP_PRED.CODIGO_PREDIO_PROPIETARIO = PRED.CODIGO_PREDIO
					INNER JOIN GESTIONPREDIAL.PERSONAS PERS ON PERS.CODIGO_PERSONA = PROP_PRED.CODIGO_PERSONA_PROPIETARIO
					WHERE PRED.CODIGO_PREDIO =  GP.codigo_predio AND PROP_PRED.codigo_persona_propietario <> 0	AND PROP_PRED.codigo_rol_persona= 2
					ORDER BY 1	+ 
							    CASE 
							        WHEN (
							            SELECT COUNT(DISTINCT PERS.CODIGO_PERSONA) 
							            FROM GESTIONPREDIAL.PROPIETARIOS_PREDIOS PROP_PRED 
							            INNER JOIN GESTIONPREDIAL.PREDIOS PRED ON PROP_PRED.CODIGO_PREDIO_PROPIETARIO = PRED.CODIGO_PREDIO
							            INNER JOIN GESTIONPREDIAL.PERSONAS PERS ON PERS.CODIGO_PERSONA = PROP_PRED.CODIGO_PERSONA_PROPIETARIO
							            WHERE 
							                PRED.CODIGO_PREDIO = GP.codigo_predio 
							                AND PROP_PRED.codigo_persona_propietario <> 0	
							                AND PROP_PRED.codigo_rol_persona = 2
							        ) > 1 THEN ' Y OTROS'
							        ELSE ''
							    END	

--- EJEMPLO 2
SELECT 
    ISNULL(
        RTRIM(LTRIM(
            STUFF((
                SELECT TOP 1 PERS.NOMBRES + ' ' 
                FROM GESTIONPREDIAL.PROPIETARIOS_PREDIOS PROP_PRED 
                INNER JOIN GESTIONPREDIAL.PREDIOS PRED ON PROP_PRED.CODIGO_PREDIO_PROPIETARIO = PRED.CODIGO_PREDIO
                INNER JOIN GESTIONPREDIAL.PERSONAS PERS ON PERS.CODIGO_PERSONA = PROP_PRED.CODIGO_PERSONA_PROPIETARIO
                WHERE 
                    PRED.CODIGO_PREDIO = 247734 
                    AND PROP_PRED.codigo_persona_propietario <> 0	
                    AND PROP_PRED.codigo_rol_persona = 2
                ORDER BY 1
                FOR XML PATH('')
            ), 1, 0, '')
        )),
    '') + 
    CASE 
        WHEN (
            SELECT COUNT(DISTINCT PERS.CODIGO_PERSONA) 
            FROM GESTIONPREDIAL.PROPIETARIOS_PREDIOS PROP_PRED 
            INNER JOIN GESTIONPREDIAL.PREDIOS PRED ON PROP_PRED.CODIGO_PREDIO_PROPIETARIO = PRED.CODIGO_PREDIO
            INNER JOIN GESTIONPREDIAL.PERSONAS PERS ON PERS.CODIGO_PERSONA = PROP_PRED.CODIGO_PERSONA_PROPIETARIO
            WHERE 
                PRED.CODIGO_PREDIO = 247734 
                AND PROP_PRED.codigo_persona_propietario <> 0	
                AND PROP_PRED.codigo_rol_persona = 2
        ) > 1 THEN ' Y OTROS'
        ELSE ''
    END AS nombre_poseedor